### ISSUE TITLE
Add Helixer model from history

### ISSUE THREAD

**Issue by arslan9732** [genouest/galaxy-tools#51]
Hi,
Could you please add an option in the Helixer tool that the user can upload lineage model from history tab?
For example, at the moment there are 4 lineage models available (land plant, vertebrate, invertebrate, and fungi) if someone wants to use an old model or a newly trained model file then it should be allowed to take the model file from the history tab.

```[tasklist]
### Tasks
- [ ] https://github.com/genouest/galaxy-tools/pull/50
```

**Comment by abretaud** [comment]
Good idea, ping @rlibouba: would you have the time to look into it?

**Comment by rlibouba** [comment]
Yes, that's a good idea. I'll look into adding this functionality. 
I'll share the PR with you once it's created. I might look at it around mid-July.

**Comment by abretaud** [comment]
That's done :heavy_check_mark:
