### ISSUE TITLE
Busco - TypeError: access: can't specify None for path argument

### ISSUE THREAD

**Issue by mictadlo** [genouest/galaxy-tools#7]
Hi @abretaud,
I tried to run Busco in Galaxy, but I received the following error massage:

```
Dataset 3: Busco on data 1: full table
Tool execution generated the following error message:

Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/mnt/galaxy/tools/busco/1.1b1/abretaud/package_busco_1_1b1/cbb7af96327a/BUSCO.py", line 165, in <module>
    if mode=='genome' and os.access(os.environ.get('AUGUSTUS_CONFIG_PATH'),os.W_OK)==False:
TypeError: access: can't specify None for path argument
ImportError: No module named site

The tool produced the following additional output:

arthropoda
```

Did I do anything wrong?

Thank you in advance.

Best wishes,

Mic

**Comment by abretaud** [comment]
Hi,
It looks like the AUGUSTUS_CONFIG_PATH variable is not defined, is augustus properly installed in galaxy?

**Comment by mictadlo** [comment]
Yes, it seems that augustus is properly installed in galaxy

![Imgur](http://i.imgur.com/rty9J95.png)
![Imgur](http://i.imgur.com/UWPyABG.png)

**Comment by abretaud** [comment]
Do you still have this problem on 16.01?

**Comment by mictadlo** [comment]
Yes, I still have it.

**Comment by abretaud** [comment]
Hi,
I have updated the busco wrapper to v2.0 on [IUC](https://github.com/galaxyproject/tools-iuc/pull/1111)
You should use this new version that should work much better.
Note that it uses conda now, so your galaxy server will need to be configured to use conda dependencies.
Cheers
Anthony

**Comment by abretaud** [comment]
Just a precision: the new busco version is on the main toolshed, with iuc as owner (instead of abretaud)

**Comment by mictadlo** [comment]
Thank you for the news. Will you soon add BUSCO 2.0 as a wrapper instead 1.1b?

**Comment by abretaud** [comment]
Hum, that's what I meant, v2.0 is online now

**Comment by mictadlo** [comment]
Sorry I looked at github, but on Mercurial it say 2.0.
