### ISSUE TITLE
Busco - This tool was disabled before the job completed.  Please contact your Galaxy administrator.

### ISSUE THREAD

**Issue by mictadlo** [genouest/galaxy-tools#8]
Hi @abretaud,
I installed Busco on Galaxy (16.01) and ran it with Arthropoda, but I got this error:
      
    This tool was disabled before the job completed.  Please contact your Galaxy administrator.

Thank you in advance.

Best wishes,

Mic

**Comment by abretaud** [comment]
Hi,
This looks like a galaxy problem i.e. it cannot find the tool
Do you have multiple galaxy process running? Maybe restarting galaxy can solve this error
Anthony

**Comment by mictadlo** [comment]
Hi, I restarted it, but now I got back this error https://github.com/genouest/galaxy-tools/issues/7#issuecomment-227396367 .

Mic

**Comment by Capriciousman** [comment]
I am also, facing this error.
![image](https://user-images.githubusercontent.com/44158088/82456588-0ff8e180-9ad2-11ea-9ff8-755351c6c796.png)

**Comment by Capriciousman** [comment]
Yes, Creating new history solves it.
Is there is any session limit?
